const ActionTypes = {
    GET_DIALOGS: 'GET_DIALOGS',
    SELECT_DIALOG: 'SELECT_DIALOG',
    SEND_MESSAGE: 'SEND_MESSAGE',
    GET_MESSAGES: 'GET_MESSAGES',
    GET_FRIENDS: 'GET_FRIENDS',
    GET_FRIENDS_LIST: 'GET_FRIENDS_LIST'
};

export default ActionTypes;
