const ActionTypes = {
    GET_DIALOGS: 'GET_DIALOGS',
    SELECT_DIALOG: 'SELECT_DIALOG',
    SEND_MESSAGE: 'SEND_MESSAGE',
    GET_MESSAGES: 'GET_MESSAGES',
    GET_FRIENDS: 'GET_FRIENDS',
    SEARCH_FRIENDS: 'SEARCH_FRIENDS',
    GET_FRIENDS_LIST: 'GET_FRIENDS_LIST',
    START_LONG_POLL: 'START_LONG_POLL',
    GET_ALBUMS: 'GET_ALBUMS',
    GET_PHOTOS: 'GET_PHOTOS',
    GET_ALBUM_PHOTOS: 'GET_ALBUM_PHOTOS',
    CLEAR_PHOTOS_STORAGE: 'CLEAR_PHOTOS_STORAGE',
    LONG_POLL_MESSAGE: 'LONG_POLL_MESSAGE',
    GET_DOCUMENTS: 'GET_DOCUMENTS',
    SEND_DOCUMENT: 'SEND_DOCUMENT'
};

export default ActionTypes;